import { writeFileSync } from "node:fs";
import type { Config } from "../config.js";
import type { SecretProvider } from "../providers/types.js";
import { log, success, warn } from "../utils.js";

export interface PullOptions {
  env: string;
  dryRun: boolean;
  verbose: boolean;
}

export async function pull(
  provider: SecretProvider,
  config: Config,
  opts: PullOptions,
): Promise<void> {
  const envConfig = config.environments[opts.env];
  if (!envConfig) {
    throw new Error(
      `Unknown environment "${opts.env}". ` +
        `Available: ${Object.keys(config.environments).join(", ")}`,
    );
  }

  log(`Fetching secrets from ${provider.name} (${envConfig.item})...`);
  const secrets = await provider.fetch({
    vault: config.vault,
    item: envConfig.item,
  });

  if (secrets.size === 0) {
    warn(`No secrets found in ${provider.name} item "${envConfig.item}".`);
    return;
  }

  log(`Found ${secrets.size} secret(s).`);

  // Build .dev.vars content
  const timestamp = new Date().toISOString();
  const lines = [
    `# Generated by sync-cf-secrets from ${provider.name} at ${timestamp}`,
    `# Source: vault="${config.vault}" item="${envConfig.item}"`,
    "# Do not commit this file.",
    "",
  ];

  for (const [name, value] of secrets) {
    lines.push(`${name}=${value}`);
  }

  lines.push(""); // trailing newline
  const content = lines.join("\n");

  if (opts.dryRun) {
    log(`\nDry run — would write to ${config.devVarsPath}:`);
    for (const name of secrets.keys()) {
      log(`  ${name}`);
    }
    return;
  }

  writeFileSync(config.devVarsPath, content, "utf-8");
  success(`Wrote ${secrets.size} secret(s) to ${config.devVarsPath}`);
}
