import { describe, it, expect, vi, beforeEach } from "vitest";
import { writeFileSync } from "node:fs";
import { pull } from "./pull.js";
import type { Config } from "../config.js";
import type { SecretProvider } from "../providers/types.js";

vi.mock("node:fs", () => ({
  writeFileSync: vi.fn(),
}));

vi.mock("../utils.js", () => ({
  exec: vi.fn(),
  execSilent: vi.fn(),
  cliExists: vi.fn(),
  log: vi.fn(),
  warn: vi.fn(),
  error: vi.fn(),
  success: vi.fn(),
}));

const mockWriteFileSync = vi.mocked(writeFileSync);

function makeConfig(overrides?: Partial<Config>): Config {
  return {
    vault: "test-vault",
    prefix: "test",
    wranglerConfig: "/fake/wrangler.toml",
    devVarsPath: "/fake/.dev.vars",
    environments: {
      local: { item: "test local" },
      staging: { item: "test staging" },
    },
    ...overrides,
  };
}

function makeProvider(overrides?: Partial<SecretProvider>): SecretProvider {
  return {
    name: "MockProvider",
    cli: "mock",
    validate: vi.fn().mockResolvedValue(undefined),
    fetch: vi.fn().mockResolvedValue(new Map()),
    exists: vi.fn().mockResolvedValue(false),
    save: vi.fn().mockResolvedValue(undefined),
    listFields: vi.fn().mockResolvedValue([]),
    ...overrides,
  };
}

beforeEach(() => {
  vi.clearAllMocks();
  vi.useFakeTimers();
  vi.setSystemTime(new Date("2025-01-15T10:30:00.000Z"));
});

describe("pull", () => {
  it("throws on unknown environment", async () => {
    await expect(
      pull(makeProvider(), makeConfig(), { env: "nope", dryRun: false, verbose: false }),
    ).rejects.toThrow('Unknown environment "nope"');
  });

  it("returns early when no secrets found", async () => {
    const { warn } = await import("../utils.js");
    const provider = makeProvider({
      fetch: vi.fn().mockResolvedValue(new Map()),
    });
    await pull(provider, makeConfig(), { env: "staging", dryRun: false, verbose: false });
    expect(warn).toHaveBeenCalledWith(expect.stringContaining("No secrets found"));
    expect(mockWriteFileSync).not.toHaveBeenCalled();
  });

  it("writes .dev.vars file with correct format", async () => {
    const secrets = new Map([
      ["API_KEY", "sk-123"],
      ["DB_URL", "postgres://localhost"],
    ]);
    const provider = makeProvider({
      fetch: vi.fn().mockResolvedValue(secrets),
    });

    await pull(provider, makeConfig(), { env: "staging", dryRun: false, verbose: false });

    expect(mockWriteFileSync).toHaveBeenCalledWith(
      "/fake/.dev.vars",
      expect.stringContaining("API_KEY=sk-123"),
      "utf-8",
    );
    const content = mockWriteFileSync.mock.calls[0][1] as string;
    expect(content).toContain("# Generated by sync-cf-secrets");
    expect(content).toContain("2025-01-15T10:30:00.000Z");
    expect(content).toContain("# Do not commit this file.");
    expect(content).toContain("DB_URL=postgres://localhost");
    expect(content.endsWith("\n")).toBe(true);
  });

  it("dry run logs names without writing file", async () => {
    const { log } = await import("../utils.js");
    const secrets = new Map([["API_KEY", "sk-123"]]);
    const provider = makeProvider({
      fetch: vi.fn().mockResolvedValue(secrets),
    });

    await pull(provider, makeConfig(), { env: "staging", dryRun: true, verbose: false });

    expect(mockWriteFileSync).not.toHaveBeenCalled();
    expect(log).toHaveBeenCalledWith(expect.stringContaining("Dry run"));
    expect(log).toHaveBeenCalledWith("  API_KEY");
  });
});
